baseURL = 'https://ccchapman.ca/'
languageCode = 'en-ca'
title = 'Chris Chapman'
theme = 'ccchapman.ca'

[taxonomies]

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'github-dark'
    tabWidth = 2
